version: '3.9'
services:

  backend:
    container_name: backend
    networks:
      - fiil
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: denon start
    volumes:
      - /Users/vladhutsal/playground/fiiiiil/backend/:/backend
    ports:
      - 8000:8000
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
        - /Users/vladhutsal/playground/fiiiiil/frontend/:/frontend
    networks:
      - fiil
    ports:
      - 8080:8080
    
  nginx:
    image: nginx:latest
    networks:
      - fiil
    depends_on:
      - backend
      - frontend
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

networks:
  fiil: