version: '3.9'
services:

  backend:
    container_name: backend
    networks:
      - fiil
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: denon start
    volumes:
      - ./backend/:/backend
    ports:
      - 8000:8000
    depends_on:
      - mongodb
  
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    command: npm run serve
    volumes:
        - ./frontend/:/frontend
    networks:
      - fiil
    ports:
      - 8080:8080

  mongodb:
    image : mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./database:/data/db
    networks:
      - fiil
    ports:
      - 27017:27017
    
  nginx:
    image: nginx:latest
    networks:
      - fiil
    depends_on:
      - backend
      - frontend
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

networks:
  fiil: